# Generated by Django 2.2.2 on 2019-07-02 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('AppFlowChart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapchoicequestion',
            name='nextQuestion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='NextQuestion_id',
                                    to='AppFlowChart.Question'),
        ),
        migrations.AlterField(
            model_name='mapchoicequestion',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Question_id',
                                    to='AppFlowChart.Question'),
        ),
    ]
